/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package contents;

import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import swing.ScrollBar;

/**
 *
 * @author Richard Reynald
 */
public class Cashier_PointOfSale extends javax.swing.JPanel {

    private int realUserId;

    public Cashier_PointOfSale(int realUserId) {
        initComponents();
        this.realUserId = realUserId;
        sp.setHorizontalScrollBar(new ScrollBar());
        sp.setVerticalScrollBar(new ScrollBar());
        sp1.setHorizontalScrollBar(new ScrollBar());
        sp1.setVerticalScrollBar(new ScrollBar());
    }
    private static final String DATABASE_NAME = "database";
    private static final String dbUsername = "root";
    private static final String dbPassword = "admin";
    private static final String MYSQL_SERVER_HOSTNAME = "DESKTOP-MVBR3DH"; // Replace with your MySQL server's hostname
    private static final int MYSQL_SERVER_PORT = 3306;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        sp1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        receiptTextArea = new javax.swing.JTextArea();
        txtBarcode = new swing.TextField();
        txtQuantity = new swing.TextField();
        totalPriceTextField = new swing.TextField();
        cashierButton1 = new swing.CashierButton();
        cashierButton2 = new swing.CashierButton();
        cashierButton3 = new swing.CashierButton();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sp1.setViewportView(productTable);

        receiptTextArea.setColumns(20);
        receiptTextArea.setRows(5);
        jScrollPane3.setViewportView(receiptTextArea);

        txtBarcode.setLabelText("Barcode");
        txtBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBarcodeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBarcodeKeyReleased(evt);
            }
        });

        txtQuantity.setText("1");
        txtQuantity.setLabelText("Quantity");

        totalPriceTextField.setLabelText("Total Price");

        cashierButton1.setText("Add");
        cashierButton1.setRadius(25);
        cashierButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierButton1ActionPerformed(evt);
            }
        });

        cashierButton2.setText("Remove");
        cashierButton2.setRadius(25);
        cashierButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierButton2ActionPerformed(evt);
            }
        });

        cashierButton3.setText("Checkout");
        cashierButton3.setRadius(25);
        cashierButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sp1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(txtBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(cashierButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cashierButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(totalPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                        .addGap(340, 340, 340)
                        .addComponent(cashierButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cashierButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cashierButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(sp1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(totalPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashierButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(399, 399, 399))
        );

        sp.setViewportView(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
private void addToCart() {
        // Get the barcode from the barcode text field
        String barcode = txtBarcode.getText().trim();

        // Database connection details
        String url = "jdbc:mysql://" + MYSQL_SERVER_HOSTNAME + ":" + MYSQL_SERVER_PORT + "/" + DATABASE_NAME;

        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            // Establish a connection to the database
            conn = DriverManager.getConnection(url, dbUsername, dbPassword);

            // SQL query to fetch product information by barcode
            String sql = "SELECT name, price, stocks FROM product_information WHERE barcode = ?";

            // Prepare the statement
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, barcode);

            // Execute the query
            rs = pstmt.executeQuery();

            // Check if a match is found
            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "Invalid barcode.");
                return;
            }

            // Get the product details from the result set
            String name = rs.getString("name");
            double price = rs.getDouble("price");
            int stocks = rs.getInt("stocks");

            // Get the quantity from the quantity text field
            String quantityStr = txtQuantity.getText().trim();

            // Validate the quantity
            int quantity;
            try {
                quantity = Integer.parseInt(quantityStr);
                if (quantity <= 0) {
                    JOptionPane.showMessageDialog(this, "Quantity must be a positive number.");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Quantity must be an integer.");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) productTable.getModel();
            boolean productExists = false;
            int totalQuantity = quantity;

            // Search for the product in the table by barcode
            for (int i = 0; i < model.getRowCount(); i++) {
                if (model.getValueAt(i, 0).equals(name)) {
                    // Product found, update the total quantity
                    int existingQuantity = (int) model.getValueAt(i, 2);
                    totalQuantity += existingQuantity;

                    // Check if the total quantity exceeds the available stock
                    if (totalQuantity > stocks) {
                        JOptionPane.showMessageDialog(this, "Insufficient stock available.");
                        return;
                    }

                    // Update the quantity and total price
                    double newTotalPrice = price * totalQuantity;
                    model.setValueAt(totalQuantity, i, 2);
                    model.setValueAt(newTotalPrice, i, 3);
                    productExists = true;
                    break;
                }
            }

            if (!productExists) {
                // Check if the input quantity exceeds the available stock
                if (quantity > stocks) {
                    JOptionPane.showMessageDialog(this, "Insufficient stock available.");
                    return;
                }

                // Product not found, add a new row
                double totalPrice = price * quantity;
                totalPrice = Double.parseDouble(String.format("%.2f", totalPrice));
                model.addRow(new Object[]{name, price, quantity, totalPrice});
            }

            // Sum all the total price values in the table and display in totalPriceTextField
            double sumTotalPrice = 0;
            for (int i = 0; i < model.getRowCount(); i++) {
                sumTotalPrice += (double) model.getValueAt(i, 3);
            }

            // Update the total price text field
            totalPriceTextField.setText(String.format("%.2f", sumTotalPrice));

            // Clear the barcode and quantity fields
            txtBarcode.setText("");
            txtQuantity.setText("1");

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }


    private void cashierButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierButton1ActionPerformed
        addToCart();
    }//GEN-LAST:event_cashierButton1ActionPerformed

    private void cashierButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierButton2ActionPerformed
        // Get the selected row index
        int selectedRow = productTable.getSelectedRow();

        // Check if a row is selected
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "No row selected.");
            return;
        }

        // Prompt the user for confirmation
        int confirm = JOptionPane.showConfirmDialog(this, "Do you want to remove the selected product from the cart?", "Confirm Remove", JOptionPane.YES_NO_OPTION);

        // If the user confirms, remove the row
        if (confirm == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) productTable.getModel();

            // Remove the selected row
            model.removeRow(selectedRow);

            // Update the total price text field
            double sumTotalPrice = 0;
            for (int i = 0; i < model.getRowCount(); i++) {
                sumTotalPrice += (double) model.getValueAt(i, 3);
            }
            totalPriceTextField.setText(String.format("%.2f", sumTotalPrice));
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
        // Prompt user for payment amount
        String paymentStr = JOptionPane.showInputDialog(this, "Enter payment amount:");
        double paymentAmount;
        try {
            paymentAmount = Double.parseDouble(paymentStr);
            if (paymentAmount <= 0) {
                JOptionPane.showMessageDialog(this, "Invalid payment amount.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid payment amount.");
            return;
        }

        // Get total price from totalPriceTextField
        double totalPrice = Double.parseDouble(totalPriceTextField.getText());

        // Validate payment amount
        if (paymentAmount < totalPrice) {
            JOptionPane.showMessageDialog(this, "Payment amount is less than the total price.");
            return;
        }

        // Proceed with checkout process
        String cashierName = getCashierName(realUserId);
        if (cashierName == null) {
            JOptionPane.showMessageDialog(this, "Cashier not found.");
            return;
        }
        // Display change to user
        double change = paymentAmount - totalPrice;
        JOptionPane.showMessageDialog(this, "Checkout successful! Change: " + String.format("%.2f", change));

        int receiptId = insertSalesReceipt(totalPrice, cashierName, paymentAmount, change);
        if (receiptId == -1) {
            JOptionPane.showMessageDialog(this, "Error creating sales receipt.");
            return;
        }

        if (!insertSalesDetails(receiptId)) {
            JOptionPane.showMessageDialog(this, "Error adding sales details.");
            return;
        }

        // Update receiptTextArea
        updateReceiptTextArea(receiptId, cashierName, paymentAmount, change);

        // Generate receipt for printing or display
        //generateReceipt(receiptId, totalPrice, paymentAmount, cashierName, productTable, receiptTextArea);
        // Clear product table and reset total price
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        model.setRowCount(0);
        totalPriceTextField.setText("0.00");
    }//GEN-LAST:event_cashierButton2ActionPerformed

    private void cashierButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierButton3ActionPerformed
        // Prompt user for payment amount
        String paymentStr = JOptionPane.showInputDialog(this, "Enter payment amount:");
        double paymentAmount;
        try {
            paymentAmount = Double.parseDouble(paymentStr);
            if (paymentAmount <= 0) {
                JOptionPane.showMessageDialog(this, "Invalid payment amount.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid payment amount.");
            return;
        }

        // Get total price from totalPriceTextField
        double totalPrice = Double.parseDouble(totalPriceTextField.getText());

        // Validate payment amount
        if (paymentAmount < totalPrice) {
            JOptionPane.showMessageDialog(this, "Payment amount is less than the total price.");
            return;
        }

        // Proceed with checkout process
        String cashierName = getCashierName(realUserId);
        if (cashierName == null) {
            JOptionPane.showMessageDialog(this, "Cashier not found.");
            return;
        }
        // Display change to user
        double change = paymentAmount - totalPrice;
        JOptionPane.showMessageDialog(this, "Checkout successful! Change: " + String.format("%.2f", change));

        int receiptId = insertSalesReceipt(totalPrice, cashierName, paymentAmount, change);
        if (receiptId == -1) {
            JOptionPane.showMessageDialog(this, "Error creating sales receipt.");
            return;
        }

        if (!insertSalesDetails(receiptId)) {
            JOptionPane.showMessageDialog(this, "Error adding sales details.");
            return;
        }

        // Update receiptTextArea
        updateReceiptTextArea(receiptId, cashierName, paymentAmount, change);

        // Generate receipt for printing or display
        //generateReceipt(receiptId, totalPrice, paymentAmount, cashierName, productTable, receiptTextArea);
        // Clear product table and reset total price
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        model.setRowCount(0);
        totalPriceTextField.setText("0.00");
    }//GEN-LAST:event_cashierButton3ActionPerformed

    private void txtBarcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarcodeKeyPressed
        String barcode = txtBarcode.getText();
        System.out.println(evt.getKeyCode() == KeyEvent.VK_ENTER);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String bad = txtQuantity.getText();
            if (bad != "1") {
                addToCart();
            } else {

                txtQuantity.setText("1");
                System.out.println(barcode);
                addToCart();
            }
        }
    }//GEN-LAST:event_txtBarcodeKeyPressed

    private void txtBarcodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarcodeKeyReleased

    }//GEN-LAST:event_txtBarcodeKeyReleased
    private String getCashierName(int userId) {
        String cashierName = null;
        String url = "jdbc:mysql://" + MYSQL_SERVER_HOSTNAME + ":" + MYSQL_SERVER_PORT + "/" + DATABASE_NAME;
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            conn = DriverManager.getConnection(url, dbUsername, dbPassword);
            String cashierSql = "SELECT first_name, last_name FROM user_information WHERE userid = ?";
            pstmt = conn.prepareStatement(cashierSql);
            pstmt.setInt(1, userId);
            rs = pstmt.executeQuery();

            if (rs.next()) {
                String firstName = rs.getString("first_name");
                String lastName = rs.getString("last_name");
                cashierName = firstName + " " + lastName;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        return cashierName;
    }

    private int insertSalesReceipt(double totalPrice, String cashierName, double amount, double change) {
        String url = "jdbc:mysql://" + MYSQL_SERVER_HOSTNAME + ":" + MYSQL_SERVER_PORT + "/" + DATABASE_NAME;
        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        int receiptId = -1;

        try {
            conn = DriverManager.getConnection(url, dbUsername, dbPassword);
            String receiptSql = "INSERT INTO sales_receipts (transaction_date, total_amount, cashier_name, amount_tendered, `change`) VALUES (NOW(), ?, ?, ?, ?)";
            pstmt = conn.prepareStatement(receiptSql, PreparedStatement.RETURN_GENERATED_KEYS);
            pstmt.setDouble(1, totalPrice);
            pstmt.setString(2, cashierName);
            pstmt.setDouble(3, amount);
            pstmt.setDouble(4, change);
            pstmt.executeUpdate();

            rs = pstmt.getGeneratedKeys();
            if (rs.next()) {
                receiptId = rs.getInt(1);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        return receiptId;
    }

    private boolean insertSalesDetails(int receiptId) {
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();
        String url = "jdbc:mysql://" + MYSQL_SERVER_HOSTNAME + ":" + MYSQL_SERVER_PORT + "/" + DATABASE_NAME;
        Connection conn = null;
        PreparedStatement pstmt = null;
        PreparedStatement updateStmt = null; // Separate PreparedStatement for stock update
        ResultSet rs = null;
        boolean success = true;

        try {
            conn = DriverManager.getConnection(url, dbUsername, dbPassword);
            String detailsSql = "INSERT INTO sales_details (receipt_id, product_id, product_name, quantity, price) VALUES (?, ?, ?, ?, ?)";
            String stockUpdateSql = "UPDATE product_information SET stocks = stocks - ? WHERE product_id = ?";
            pstmt = conn.prepareStatement(detailsSql);
            updateStmt = conn.prepareStatement(stockUpdateSql);

            for (int i = 0; i < model.getRowCount(); i++) {
                String productName = (String) model.getValueAt(i, 0);
                int quantity = (int) model.getValueAt(i, 2);
                double price = ((double) model.getValueAt(i, 1)) * quantity;

                // Get product_id from product_information table
                String productIdSql = "SELECT product_id FROM product_information WHERE name = ?";
                PreparedStatement productIdStmt = conn.prepareStatement(productIdSql);
                productIdStmt.setString(1, productName);
                ResultSet rsProductId = productIdStmt.executeQuery();

                int productId = 0;
                if (rsProductId.next()) {
                    productId = rsProductId.getInt("product_id");
                }

                // Insert into sales_details table
                pstmt.setInt(1, receiptId);
                pstmt.setInt(2, productId);
                pstmt.setString(3, productName);
                pstmt.setInt(4, quantity);
                pstmt.setDouble(5, price);
                pstmt.executeUpdate();

                // Update product stocks
                updateStmt.setInt(1, quantity);
                updateStmt.setInt(2, productId);
                updateStmt.executeUpdate();

                // Close ResultSet and Statement for product_id query
                rsProductId.close();
                productIdStmt.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
            success = false;
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (updateStmt != null) {
                    updateStmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        return success;
    }

    private void updateReceiptTextArea(int receiptId, String cashierName, double amountTendered, double change) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date currentDate = new Date();

        StringBuilder receiptText = new StringBuilder();
        receiptText.append("===== Sahagun's Veterinary Clinic =====\n");
        receiptText.append("Cashier: ").append(cashierName).append("\n");
        receiptText.append("Date: ").append(dateFormat.format(currentDate)).append("\n\n");

        DefaultTableModel model = (DefaultTableModel) productTable.getModel();

        // Get the width of the receiptTextArea in characters
        FontMetrics fontMetrics = receiptTextArea.getFontMetrics(receiptTextArea.getFont());
        int textAreaWidth = receiptTextArea.getWidth() / fontMetrics.charWidth('A');

        // Calculate the maximum length of the product names
        int maxProductNameLength = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            String productName = (String) model.getValueAt(i, 0);
            if (productName.length() > maxProductNameLength) {
                maxProductNameLength = productName.length();
            }
        }

        // Calculate available space for each column
        int quantityColumnWidth = 10;  // fixed width for quantity
        int totalColumnWidth = 10;     // fixed width for total
        int productColumnWidth = Math.max(maxProductNameLength, textAreaWidth - quantityColumnWidth - totalColumnWidth - 4);  // calculate based on text area width

        // Create the format strings dynamically
        String formatHeader = "%-" + productColumnWidth + "s\t%-" + quantityColumnWidth + "s\t%-" + totalColumnWidth + "s\n";
        String formatBody = "%-" + productColumnWidth + "s\t%-" + quantityColumnWidth + "d\t%-" + totalColumnWidth + ".2f\n";

        receiptText.append(String.format(formatHeader, "Product", "Quantity", "Total"));
        receiptText.append("-------------------------------------------------------\n");

        double totalPrice = 0.0;
        for (int i = 0; i < model.getRowCount(); i++) {
            String productName = (String) model.getValueAt(i, 0);
            int quantity = (int) model.getValueAt(i, 2);
            double price = (double) model.getValueAt(i, 1);
            double total = quantity * price;

            receiptText.append(String.format(formatBody, productName, quantity, total));
            totalPrice += total;
        }

        receiptText.append("\n-----------------------------------------------------\n");
        receiptText.append(String.format("%-40s%.2f\n", "Total Amount:", totalPrice));
        receiptText.append(String.format("%-40s%.2f\n", "Amount Tendered:", amountTendered));
        receiptText.append(String.format("%-40s%.2f\n", "Change:", change));
        receiptText.append("\nThank you for shopping with us!\n");
        receiptText.append("\nThis is not a valid reciept !\n");

        receiptTextArea.setText(receiptText.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.CashierButton cashierButton1;
    private swing.CashierButton cashierButton2;
    private swing.CashierButton cashierButton3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable productTable;
    private javax.swing.JTextArea receiptTextArea;
    private javax.swing.JScrollPane sp;
    private javax.swing.JScrollPane sp1;
    private swing.TextField totalPriceTextField;
    private swing.TextField txtBarcode;
    private swing.TextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
