package contents;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.*;

import java.util.UUID;
import com.itextpdf.text.Image;
import org.krysalis.barcode4j.impl.code39.Code39Bean;
import org.krysalis.barcode4j.output.bitmap.BitmapCanvasProvider;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import javax.imageio.ImageIO;
import javax.swing.*;

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

import java.util.Date;
import java.util.UUID;
import javax.swing.JOptionPane;
import swing.ScrollBar;

/**
 *
 * @author Richard Reynald
 */
public class Cashier_Add extends javax.swing.JPanel {

    /**
     * Creates new form Cashier_Add
     */
    private int realUserId;
    public Cashier_Add(int realUserId) {
        initComponents();
        this.realUserId = realUserId;
        sp.setVerticalScrollBar(new ScrollBar());
        sp.setHorizontalScrollBar(new ScrollBar());
    }
    private static final String DATABASE_NAME = "database";
    private static final String dbUsername = "root";
    private static final String dbPassword = "admin";
    private static final String MYSQL_SERVER_HOSTNAME = "DESKTOP-MVBR3DH"; // Replace with your MySQL server's hostname
    private static final int MYSQL_SERVER_PORT = 3306;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtBarcode = new swing.TextField();
        txtName = new swing.TextField();
        txtPrice = new swing.TextField();
        txtStocks = new swing.TextField();
        rbtnPerishableYes = new javax.swing.JRadioButton();
        rbtnPerishableNo = new javax.swing.JRadioButton();
        cmbCategory = new swing.Combobox();
        txtSupplierName = new swing.TextField();
        txtSupplierAddress = new swing.TextField();
        txtSupplierContact = new swing.TextField();
        jLabel13 = new javax.swing.JLabel();
        jDateChooserExpirationDate = new com.toedter.calendar.JDateChooser();
        txtCriticalLevel = new swing.TextField();
        jLabel18 = new javax.swing.JLabel();
        cashierButton1 = new swing.CashierButton();
        cashierButton2 = new swing.CashierButton();
        cashierButton3 = new swing.CashierButton();

        setPreferredSize(new java.awt.Dimension(1100, 685));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Perishable");

        txtBarcode.setLabelText("Barcode");
        txtBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarcodeActionPerformed(evt);
            }
        });

        txtName.setLabelText("Product Name");

        txtPrice.setLabelText("Price");

        txtStocks.setLabelText("Stocks");

        rbtnPerishableYes.setText("Yes");
        rbtnPerishableYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPerishableYesActionPerformed(evt);
            }
        });

        rbtnPerishableNo.setText("No");
        rbtnPerishableNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPerishableNoActionPerformed(evt);
            }
        });

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Food", "Vitamin", "Medicine", "Vaccine", "Grooming", "Accessory", "Toy" }));
        cmbCategory.setSelectedIndex(-1);
        cmbCategory.setLabelText("Category");

        txtSupplierName.setLabelText("Supplier");

        txtSupplierAddress.setLabelText("Supplier Address");

        txtSupplierContact.setLabelText("Supplier Contact");
        txtSupplierContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierContactActionPerformed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Exp Date");

        txtCriticalLevel.setLabelText("Critical Level");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("NEW PRODUCT");

        cashierButton1.setText("Generate");
        cashierButton1.setRadius(25);
        cashierButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierButton1ActionPerformed(evt);
            }
        });

        cashierButton2.setText("Search");
        cashierButton2.setRadius(25);
        cashierButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierButton2ActionPerformed(evt);
            }
        });

        cashierButton3.setText("Add Product");
        cashierButton3.setRadius(25);
        cashierButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cashierButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSupplierContact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(txtSupplierAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSupplierName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(cashierButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtnPerishableYes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtnPerishableNo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                        .addComponent(jLabel13))
                                    .addComponent(txtBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCriticalLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooserExpirationDate, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(cashierButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(160, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashierButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCriticalLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnPerishableYes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnPerishableNo))
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashierButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(txtSupplierAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(txtSupplierContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(cashierButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sp.setViewportView(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void searchSupplier() {
        String supplierName = txtSupplierName.getText();

        // Database connection details
        String url = "jdbc:mysql://" + MYSQL_SERVER_HOSTNAME + ":" + MYSQL_SERVER_PORT + "/" + DATABASE_NAME;

        Connection conn = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            // Establish a connection to the database
            conn = DriverManager.getConnection(url, dbUsername, dbPassword);

            // SQL query to search for the supplier
            String sql = "SELECT supplier_address, supplier_contact FROM suppliers WHERE supplier_name = ?";

            // Prepare the statement
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, supplierName);

            // Execute the query
            rs = pstmt.executeQuery();

            if (rs.next()) {
                // Retrieve the address and contact if the supplier exists
                String supplierAddress = rs.getString("supplier_address");
                String supplierContact = rs.getString("supplier_contact");

                // Set the text into the text fields
                txtSupplierAddress.setText(supplierAddress);
                txtSupplierContact.setText(supplierContact);
            } else {
                // If the supplier does not exist, show a message
                JOptionPane.showMessageDialog(this, "Supplier not found.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    private void rbtnPerishableYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPerishableYesActionPerformed
        rbtnPerishableYes.setSelected(true);
        rbtnPerishableNo.setSelected(false);
    }//GEN-LAST:event_rbtnPerishableYesActionPerformed

    private void rbtnPerishableNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPerishableNoActionPerformed
        rbtnPerishableYes.setSelected(false);
        rbtnPerishableNo.setSelected(true);
    }//GEN-LAST:event_rbtnPerishableNoActionPerformed

    private void txtBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarcodeActionPerformed

    private void cashierButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierButton1ActionPerformed
        System.out.println("generate");
        String strCodeText = UUID.randomUUID().toString().substring(0, 8).toUpperCase(); // Generate a random 8-character string
        txtBarcode.setText(strCodeText);
    }//GEN-LAST:event_cashierButton1ActionPerformed

    private void cashierButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierButton2ActionPerformed
        String supplierName = txtSupplierName.getText().trim(); // Trim to remove leading and trailing spaces

        // Check if supplierName is empty
        if (supplierName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a supplier name.");
            return; // Exit the method if the supplier name is empty
        }

        // Call searchSupplier only if supplierName is not empty
        searchSupplier();
    }//GEN-LAST:event_cashierButton2ActionPerformed
public void addProductAuditLog(int userId, String name) {
        String url = "jdbc:mysql://" + MYSQL_SERVER_HOSTNAME + ":" + MYSQL_SERVER_PORT + "/" + DATABASE_NAME;
        try {
            // Establish the database connection
            Connection connection = DriverManager.getConnection(url, dbUsername, dbPassword);

            // Prepare the SQL query to add login audit log
            String query = "INSERT INTO audit_logs (userid, event, action_type) VALUES (?, ?, 'add product')";
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            preparedStatement.setInt(1, userId);
            preparedStatement.setString(2, "added new product: " + name);

            // Execute the query
            int rowsAffected = preparedStatement.executeUpdate();

            // Close the database connection
            connection.close();
        } catch (SQLException e) {
            // Handle any SQL exceptions
            e.printStackTrace();
        }
    }
    private void cashierButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierButton3ActionPerformed
        String barTxt = txtBarcode.getText();
        int response = JOptionPane.showConfirmDialog(null, "Do you want to print the barcode for this product?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            System.out.println("User chose Yes.");
            convertToPDF(barTxt);
            addProdToDB();
        } else if (response == JOptionPane.NO_OPTION) {
            System.out.println("User chose No.");
            addProdToDB();
        } else if (response == JOptionPane.CLOSED_OPTION) {
            JOptionPane.showMessageDialog(null, "User closed the dialog. No action performed.", "Closed", JOptionPane.INFORMATION_MESSAGE);
            System.out.println("User closed the dialog. No action performed.");
        }


    }//GEN-LAST:event_cashierButton3ActionPerformed

    private void txtSupplierContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierContactActionPerformed

    private void addProdToDB() {
        // Get the necessary information from the text fields and other input controls
        String barcode = txtBarcode.getText().trim();
        String name = txtName.getText().trim();
        String priceStr = txtPrice.getText().trim();
        String stocksStr = txtStocks.getText().trim();
        String criticalLevelStr = txtCriticalLevel.getText().trim();

        boolean perishable = rbtnPerishableYes.isSelected(); // Assuming you have two radio buttons for Yes and No
        java.util.Date expirationDate = jDateChooserExpirationDate.getDate();
        String supplierName = txtSupplierName.getText().trim();
        String supplierAddress = txtSupplierAddress.getText().trim();
        String supplierContact = txtSupplierContact.getText().trim();
        String category = (String) cmbCategory.getSelectedItem(); // Assuming you have a JComboBox for category

        // Validate name
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a product name.");
            return;
        }

        // Validate price
        BigDecimal price;
        try {
            price = new BigDecimal(priceStr);
            if (price.compareTo(BigDecimal.ZERO) <= 0) {
                JOptionPane.showMessageDialog(this, "Price must be a positive number.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid price format.");
            return;
        }

        // Validate stocks
        int stocks;
        try {
            stocks = Integer.parseInt(stocksStr);
            if (stocks <= 0) {
                JOptionPane.showMessageDialog(this, "Stocks must be a positive number.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid stocks format.");
            return;
        }

        // Validate critical level
        int criticalLevel;
        try {
            criticalLevel = Integer.parseInt(criticalLevelStr);
            if (criticalLevel <= 0) {
                JOptionPane.showMessageDialog(this, "Critical level must be a positive number.");
                return;
            }
            if (criticalLevel > stocks) {
                JOptionPane.showMessageDialog(this, "Critical level cannot be greater than stocks.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid critical level format.");
            return;
        }

        // Validate perishable
        if (!rbtnPerishableYes.isSelected() && !rbtnPerishableNo.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select if the product is perishable.");
            return;
        }

        // Validate expiration date
        if (perishable && expirationDate != null) {
            Date today = new Date();
            if (expirationDate.before(today)) {
                JOptionPane.showMessageDialog(this, "Expiration date cannot be a past date.");
                return;
            }
        }

        // Validate supplier name, address, and contact
        if (supplierName.isEmpty() || supplierAddress.isEmpty() || supplierContact.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter supplier information.");
            return;
        }

        // Validate supplier contact format (11 digits)
        if (!supplierContact.matches("\\d{11}")) {
            JOptionPane.showMessageDialog(this, "Supplier contact must be 11 digits.");
            return;
        }

        // Database connection details
        String url = "jdbc:mysql://" + MYSQL_SERVER_HOSTNAME + ":" + MYSQL_SERVER_PORT + "/" + DATABASE_NAME;

        Connection conn = null;
        PreparedStatement pstmt = null;
        PreparedStatement checkSupplierStmt = null;
        ResultSet rs = null;

        try {
            // Establish a connection to the database
            conn = DriverManager.getConnection(url, dbUsername, dbPassword);

            // Check if the supplier already exists
            String checkSupplierSql = "SELECT supplier_id FROM suppliers WHERE supplier_name = ?";
            checkSupplierStmt = conn.prepareStatement(checkSupplierSql);
            checkSupplierStmt.setString(1, supplierName);
            rs = checkSupplierStmt.executeQuery();

            int supplierId = -1;
            if (rs.next()) {
                // Supplier exists, get the supplier ID
                supplierId = rs.getInt("supplier_id");
            } else {
                // Supplier does not exist, insert a new supplier
                String insertSupplierSql = "INSERT INTO suppliers (supplier_name, supplier_address, supplier_contact) VALUES (?, ?, ?)";
                pstmt = conn.prepareStatement(insertSupplierSql, Statement.RETURN_GENERATED_KEYS);
                pstmt.setString(1, supplierName);
                pstmt.setString(2, supplierAddress);
                pstmt.setString(3, supplierContact);
                pstmt.executeUpdate();

                // Get the generated supplier ID
                rs = pstmt.getGeneratedKeys();
                if (rs.next()) {
                    supplierId = rs.getInt(1);
                }
            }

            // SQL query to insert data into the product_information table
            String sql = "INSERT INTO product_information (barcode, name, price, stocks, critical_level, perishable, expiration_date, category, supplier_name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

            // Prepare the statement
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, barcode);
            pstmt.setString(2, name);
            pstmt.setBigDecimal(3, price);
            pstmt.setInt(4, stocks);
            pstmt.setInt(5, criticalLevel);
            pstmt.setBoolean(6, perishable);

            if (perishable) {
                // Convert the java.util.Date to java.sql.Date if the product is perishable
                java.sql.Date sqlExpirationDate = new java.sql.Date(expirationDate.getTime());
                pstmt.setDate(7, sqlExpirationDate);
            } else {
                // Set expiration_date to null if the product is not perishable
                pstmt.setNull(7, java.sql.Types.DATE);
            }

            pstmt.setString(8, category);
            pstmt.setString(9, supplierName);

            // Execute the update
            int rowsAffected = pstmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Product information added successfully.");
                addProductAuditLog(realUserId,name);
                clearTextFields();
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (checkSupplierStmt != null) {
                    checkSupplierStmt.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    public InputStream generateCode39Barcode(String barcodeText) {
        try {
            Code39Bean bean = new Code39Bean();
            final int dpi = 150;

            // Configure the barcode generator
            bean.setModuleWidth(0.2);
            bean.setWideFactor(3);
            bean.doQuietZone(false);

            // Create a ByteArrayOutputStream to hold the generated barcode image
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

            // Generate the barcode
            BitmapCanvasProvider canvas = new BitmapCanvasProvider(
                    outputStream, "image/x-png", dpi, BufferedImage.TYPE_BYTE_BINARY, false, 0);
            bean.generateBarcode(canvas, barcodeText);
            canvas.finish();

            System.out.println(barcodeText);

            // Convert the generated barcode image to InputStream
            return new ByteArrayInputStream(outputStream.toByteArray());
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    private void clearTextFields() {
        txtBarcode.setText("");
        txtName.setText("");
        txtPrice.setText("");
        txtStocks.setText("");
        txtCriticalLevel.setText("");
        jDateChooserExpirationDate.setDate(null);
        txtSupplierName.setText("");
        txtSupplierAddress.setText("");
        txtSupplierContact.setText("");

    }

    public void convertToPDF(String barcodeText) {
        // Open a file chooser to select the folder
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int option = fileChooser.showSaveDialog(null);
        String prodName = txtName.getText();
        if (option == JFileChooser.APPROVE_OPTION) {
            File selectedFolder = fileChooser.getSelectedFile();

            // Define the PDF file path with formatted date range
            String pdfFileName = "barcode_" + prodName + ".pdf";
            String pdfFilePath = selectedFolder.getAbsolutePath() + "/" + pdfFileName;

            // Create the PDF document
            Document document = new Document();
            try {
                PdfWriter.getInstance(document, new FileOutputStream(pdfFilePath));
                document.open();

                Paragraph clinicTitle = new Paragraph("Product barcodes for: " + prodName + "", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16));
                clinicTitle.setAlignment(Element.ALIGN_CENTER);
                document.add(clinicTitle);
                document.add(Chunk.NEWLINE); //

                // Generate and add barcode to the PDF
                InputStream barcodeInputStream = generateCode39Barcode(barcodeText);
                if (barcodeInputStream != null) {
                    BufferedImage bufferedBarcodeImage = ImageIO.read(barcodeInputStream);
                    ByteArrayOutputStream baos = new ByteArrayOutputStream();
                    ImageIO.write(bufferedBarcodeImage, "png", baos);
                    Image barcodeImage = Image.getInstance(baos.toByteArray());
                    barcodeImage.setAlignment(Element.ALIGN_CENTER);
                    document.add(barcodeImage);
                    document.add(barcodeImage);
                    document.add(barcodeImage);
                    document.add(barcodeImage);
                    document.add(barcodeImage);
                }

                // Close the document
                document.close();

                JOptionPane.showMessageDialog(null, "PDF saved successfully as '" + pdfFileName + "'.");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.CashierButton cashierButton1;
    private swing.CashierButton cashierButton2;
    private swing.CashierButton cashierButton3;
    private swing.Combobox cmbCategory;
    private com.toedter.calendar.JDateChooser jDateChooserExpirationDate;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton rbtnPerishableNo;
    private javax.swing.JRadioButton rbtnPerishableYes;
    private javax.swing.JScrollPane sp;
    private swing.TextField txtBarcode;
    private swing.TextField txtCriticalLevel;
    private swing.TextField txtName;
    private swing.TextField txtPrice;
    private swing.TextField txtStocks;
    private swing.TextField txtSupplierAddress;
    private swing.TextField txtSupplierContact;
    private swing.TextField txtSupplierName;
    // End of variables declaration//GEN-END:variables
}
